### PR TITLE
Added alphabet keypad

### PR DESCRIPTION
**Pull request by simon-xiong-ca**
Added alphabet keypad, css for the buttons, and function that returns the letter chosen and disables the button after being pressed.
Enter "135.23.130.81/js-tuesday-hangman/hangman" in URL to see a preview.

### CODE REVIEW

**Comment by nannigan** [comment]
looks really nice!

**Comment by simon-xiong-ca** [comment]
thanks :)

**Comment by dsberger** [comment]
This looks so great, Simon! I [previewed it here](https://htmlpreview.github.io/?https://github.com/code-newbies/js-tuesday-hangman/blob/alphabet-keypad/hangman.html) and it looks and works great.

**Comment by simon-xiong-ca** [comment]
Thanks. How did you set up that preview!? It makes things so much easier.

**Comment by dsberger** [comment]
Go to [https://htmlpreview.github.io](https://htmlpreview.github.io) and paste the direct link to the html file. It has to be the file in the pull request though.

**Comment by coryunderwood** [comment]
Good so far.

Extra credit:  Since you have access to jQuery, how would you change the markup to not need to use on the onclick handlers in the markup?

**Comment by simon-xiong-ca** [comment]
Good idea, I'll look into jQuery. What's the advantage of using jQuery versus the event attributes?

**Comment by coryunderwood** [comment]
A few things.

If you change the event handler, you'd need to change the onclick value in 26 places.  Additionally, you have script logic mixed in with the HTML markup.

By taking advantage of jQuery, you can have a single handler process all 26 values, as well as keep the game logic separate from the markup that forms the keypad.

While likely not critical for this project, you will find it advantageous to keep all your logic out of the markup, because it makes maintenance on the logic far easier on larger projects.

Check out the API for jQuery's .on() function.  http://api.jquery.com/on/

See if you can get that to work, on the 'click' event, pulling in the value from the clicked DOM Node.

**Comment by Lorddan** [comment]
I've spent a couple hours throwing a few ideas together, still have to figure out the reset and a way of pulling in different words. Checkout dansBranch, there are plenty of bug's that i'm aware of. I'll go threw and tidy up my css and scripts and add more comment's soon as i get some more time, it works in Chrome although i'm sure where i've called "setHangman(fails); buildKeypad() buildWord();" will break in firefox. 
I did this out of boredom with a friend, and i'm not particularly familiar with git. feedback would be great.

**Comment by dsberger** [comment]
hi all,

This is probably good to merge, @simonxca ! We can definitely refactor with another Issue.

Dan

**Comment by simon-xiong-ca** [comment]
I'll wait until later today. As Cory said, I'm going to replace this with jQuery.

**Comment by simon-xiong-ca** [comment]
Acutally you're right. We can open another issue for that instead.

**Pull request merged**
